### Create Article
POST localhost:8080/api/v1/article
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5MjY4NDcsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgzMDEzMjQ4LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.6s_S2HLO1Vlab505WhpY56xgIJhZ0YQcMB0dcNYRyJ6v1-Ln1I1JtFcHZukDzItqQwCUd12GL7HFDBui2vs9gg
Content-Type:  application/json

//{
//  "title": "Nimadir",
//  "description": "Qisqacha Nimadir",
//  "content": "Bir bor ekan bir yoq ekan",
//  "regionId": 1,
//  "categoryId": 2,
//  "typeId": 1
//}
//{
//  "title": "Nimadir1",
//  "description": "Qisqacha Nimadir1",
//  "content": "Bir bor ekan bir yoq ekan1",
//  "regionId": 1,
//  "categoryId": 2,
//  "typeId": 1
//}
//{
//  "title": "Nimadir2",
//  "description": "Qisqacha Nimadir2",
//  "content": "Bir bor ekan bir yoq ekan2",
//  "regionId": 2,
//  "categoryId": 1,
//  "typeId": 2
//}
//{
//  "title": "Nimadir3",
//  "description": "Qisqacha Nimadir3",
//  "content": "Bir bor ekan bir yoq ekan3",
//  "regionId": 3,
//  "categoryId": 3,
//  "typeId": 3
//}
//{
//  "title": "Nimadir4",
//  "description": "Qisqacha Nimadir4",
//  "content": "Bir bor ekan bir yoq ekan4",
//  "regionId": 3,
//  "categoryId": 3,
//  "typeId": 3
//}
//{
//  "title": "Nimadir5",
//  "description": "Qisqacha Nimadir5",
//  "content": "Bir bor ekan bir yoq ekan5",
//  "regionId": 2,
//  "categoryId": 2,
//  "typeId": 2
//}
{
  "title": "Nimadir8",
  "description": "Qisqacha Nimadir8",
  "content": "Bir bor ekan bir yoq ekan8",
  "regionId": 1,
  "categoryId": 1,
  "typeId": 1,
  "photoId" : "92475d3e-1dfb-4bdf-8704-e090aed2db99"
}

### Update Article
PUT localhost:8080/api/v1/article/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NTMwMDksImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgyODM5NDA5LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.L2wRNR238NhOhZqddbZgKPNh_fdyYX1GX2JtdMpMC2ULjNu21LHb0X1l42y_aHi0kJ4oujbrdE8C7wBCrpxyBA
Content-Type:  application/json

{
  "id" : "fa43203a-125e-4a9d-ab21-78de2743dd1e",
  "title": "Allanima",
  "description": "Qisqacha Allanima",
  "content": "Bir bor ekan bir yoq ekanda",
  "regionId": 1,
  "categoryId": 2,
  "typeId": 3
}
### ChangeStatus Article
PUT localhost:8080/api/v1/article/change-Status/8a1f193b-04b1-4e5c-8bd3-94069c9f6405?status=PUBLISHED
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMxMTYyNDMsImlkIjo0LCJyb2xlIjoiUFVCTElTSEVSIiwiZXhwIjoxNjgzMjAyNjQzLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.dr-ZgEoArMS-oPA7K1n0eozOU46L20ZqudWXTXW18qB1LOjjrjNWpmuHd0u9Ku8AqvJ52--kYHWwLyiFTx4uUw
Content-Type:  application/json


### Delete Article
PUT localhost:8080/api/v1/article/delete/5ab5ca0f-c660-48ad-8cf6-850c84915a69
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NTMwMDksImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgyODM5NDA5LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.L2wRNR238NhOhZqddbZgKPNh_fdyYX1GX2JtdMpMC2ULjNu21LHb0X1l42y_aHi0kJ4oujbrdE8C7wBCrpxyBA
Content-Type:  application/json

### Get 5 Article
GET localhost:8080/api/v1/article/getLastFiveArticleByType/5

### Get 3 Article
GET localhost:8080/api/v1/article/getLastThreeArticleByType/3

### Get GetArticlesNotInList
GET localhost:8080/api/v1/article/getArticlesNotInList?idList=9d9375a0-e00f-47a9-8692-bd80456d7ac2&idList=9d9375a0-e00f-47a9-8692-bd80456d7ac2&idList=fa43203a-125e-4a9d-ab21-78de2743dd1e

### GetLast4ArticleByTypes
PUT localhost:8080/api/v1/article/findLast4ArticleByTypes/1
Content-Type:  application/json

{
"articleIdList": ["9d9375a0-e00f-47a9-8692-bd80456d7ac2","5ab5ca0f-c660-48ad-8cf6-850c84915a69"]
}

### Get GetArticlesNotInList
GET localhost:8080/api/v1/article/get4MostReadArticles

### findLast5ArticleByTypesAndRegionId Article
PUT localhost:8080/api/v1/article/findLast5ArticleByTypesAndRegionId/1?typeName=Maqola №1
Content-Type:  application/json

### PagingByRegion Article
PUT localhost:8080/api/v1/article/pagingByRegion
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMxMjI2MTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMyMDkwMTksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.LP1Yj6q3MknNVECVGw4S7_q4ZXl8HwzicxxHUCl44Vkw88PBWVQagL3Fxfj-Qf3E6mPr7J16uzHZpqBHm8PLlA
Content-Type:  application/json

### getTop5ByArticleByCategory Article
PUT localhost:8080/api/v1/article/getTop5ByArticleByCategory/3
Content-Type:  application/json

### PagingByRegion Article
PUT localhost:8080/api/v1/article/pagingByCategory
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMxMjI2MTksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMyMDkwMTksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.LP1Yj6q3MknNVECVGw4S7_q4ZXl8HwzicxxHUCl44Vkw88PBWVQagL3Fxfj-Qf3E6mPr7J16uzHZpqBHm8PLlA
Content-Type:  application/json

### getIncreaseArticleViewCountByArticleId Article
PUT localhost:8080/api/v1/article/getIncreaseArticleViewCountByArticleId/4fe1dda1-dbc7-4aa9-a6bd-e568a13b4e12
Content-Type:  application/json

### getIncreaseArticleShareCountByArticleId Article
PUT localhost:8080/api/v1/article/getIncreaseArticleShareCountByArticleId/91849840-b6dd-4a58-803a-bc3d336f659f
Content-Type:  application/json

### Create filter
POST localhost:8080/api/v1/article/filter
Content-Type:  application/json

{
  "title": "Nimadir",
  "regionId": 1
}
