### Create Article
POST localhost:8080/api/v1/articleType/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

//{
//  "nameUz": "Maqola №1",
//  "nameRu": "Статия №1",
//  "nameEng": "Article №1",
//  "visible": true
//}
//{
//  "nameUz": "Maqola №2",
//  "nameRu": "Статия №2",
//  "nameEng": "Article №2",
//  "visible": true
//}
//{
//  "nameUz": "Maqola №3",
//  "nameRu": "Статия №3",
//  "nameEng": "Article №3",
//  "visible": true
//}
{
  "nameUz": "Maqola №4",
  "nameRu": "Статия №4",
  "nameEng": "Article №4",
  "visible": true
}
### Update profil
PUT localhost:8080/api/v1/articleType/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

{
  "id" : 4,
  "nameUz": "Maqola №5",
  "nameRu": "Статия №5",
  "nameEng": "Article №5",
  "visible": true
}

### List profil
PUT localhost:8080/api/v1/articleType/delete/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

### Paging profil
PUT localhost:8080/api/v1/articleType/paging
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

### GetByLang profil
PUT localhost:8080/api/v1/articleType/getByLang/Ru
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json