###upload
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="737753.jpg"

< C:\Users\Mamurjon\Downloads\737753.jpg

###upload
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="737757.jpg"

< C:\Users\Mamurjon\Downloads\737757.jpg

###upload
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="399717.jpg"

< C:\Users\Mamurjon\Downloads\399717.jpg

### video
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="333.mp4"

< C:\Users\BigMan\Desktop\11\333.mp4

#< C:\Users\BigMan\Desktop\11\test_imge_1.jpg