### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "ali@mail.com",
  "password": "2"
}

### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "admin@gmail.com",
  "password": "1"
}

### Registration
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Mamurjon",
  "surname": "Uzokov",
  "phone": "7",
  "email": "uzokov29@gmail.com",
  "password": "7"
}

### Registration
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Admin",
  "surname": "Adminov",
  "phone": "1",
  "email": "admin@gmail.com",
  "password": "1"
}

### Registration
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "phone": "2",
  "email": "ali@mail.com",
  "password": "2"
}
### Registration
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Vali",
  "surname": "Valiyev",
  "phone": "3",
  "email": "vali@mail.com",
  "password": "3"
}

### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "mamat@mail.ru",
  "password": "5"
}

### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "vali@mail.com",
  "password": "3"
}

### Verification
GET localhost:8080//api/v1/auth/verification/
Content-Type:  application/json