### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "ali@mail.ru",
  "password": "2"
}

### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "admin@mail.ru",
  "password": "1"
}

### Registration
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Mamurjon",
  "surname": "Uzokov",
  "phone": "1213",
  "email": "uzokov29@gmail.com",
  "password": "12345"
}

### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "vali@mail.ru",
  "password": "3"
}

### Verification
POST localhost:8080/api/v1/auth/verification/
Content-Type:  application/json