### Create Category
POST localhost:8080/api/v1/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

//{
//  "nameUz": "Mahalliy",
//  "nameRu": "Местный",
//  "nameEng": "Local",
//  "visible": true
//}
//{
//  "nameUz": "Jahon",
//  "nameRu": "МИР",
//  "nameEng": "World",
//  "visible": true
//}
//{
//  "nameUz": "IQTISODIYOT",
//  "nameRu": "ЭКОНОМИКА",
//  "nameEng": "ECONOMY",
//  "visible": true
//}
{
  "nameUz": "FAN-TEXNIKA",
  "nameRu": "НАУКА И ТЕХНОЛОГИЯ",
  "nameEng": "SCIENCE AND TECHNOLOGY",
  "visible": true
}
### Update Category
PUT localhost:8080/api/v1/category/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

{
  "id" : 1,
  "nameUz": "SPORT",
  "nameRu": "ВИДЫ СПОРТА",
  "nameEng": "SPORTS",
  "visible": true
}

### List Category
PUT localhost:8080/api/v1/category/delete/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

### Paging Category
PUT localhost:8080/api/v1/category/paging
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

### GetByLang Category
PUT localhost:8080/api/v1/category/getByLang/Ru
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json