### Create CommentLike
GET localhost:8080/api/v1/comment_like/like/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNTM3NTIsImlkIjo2LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY4MzQ0MDE1MiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.k3PirJ2-6KJaaTbANRnTE0KKYB6OynfRJgNHeM2gCuCv2ocWBrtMdZ3uI9kAoNCuow20vUv9vns_rFIqUnjZ5w

### Create CommentDisLike
GET localhost:8080/api/v1/comment_like/dislike/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNTM3NTIsImlkIjo2LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY4MzQ0MDE1MiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.k3PirJ2-6KJaaTbANRnTE0KKYB6OynfRJgNHeM2gCuCv2ocWBrtMdZ3uI9kAoNCuow20vUv9vns_rFIqUnjZ5w

### Delete
DELETE localhost:8080/api/v1/comment_like/delete/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNTM3NTIsImlkIjo2LCJyb2xlIjoiVVNFUiIsImV4cCI6MTY4MzQ0MDE1MiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.k3PirJ2-6KJaaTbANRnTE0KKYB6OynfRJgNHeM2gCuCv2ocWBrtMdZ3uI9kAoNCuow20vUv9vns_rFIqUnjZ5w
