### Get EmailByName
GET localhost:8080/api/v1/email/getByEmail/vali@mail.ru

### Get EmailByDate
GET localhost:8080/api/v1/email/getByCreatedDate/2023-04-26

### Paging profil
PUT localhost:8080/api/v1/email/paging
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI1MTQ0MTUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI2MDA4MTUsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.of--AMIcJrFjHQNNfARYeXjnO5Tssh7LaqFeZN-v_xsyeRVFsx6c6Qfq5SdoLwYumf5gTdXs2ipetEasaCpIJg
Content-Type:  application/json
