### Create profle
POST localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5MDk1MjcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5OTU5MjcsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.NajD-X4FaRzEwPEs00Y9MZ_HkMC6gkfy4YZkJ2Hw_3SEZn0R4OVFD6QKcYpbi9P4pBal1zxC8bDIemjEdFzMSg
Content-Type:  application/json

//{
//  "name": "Ali",
//  "surname": "Aliyev",
//  "email": "ali@mail.ru",
//  "phone": "2",
//  "password": "2",
//  "role": "MODERATOR"
//}
{
  "name": "Vali",
  "surname": "Valiyev",
  "email": "vali@mail.ru",
  "phone": "3",
  "password": "3",
  "role": "PUBLISHER"
}

### Update profle
PUT localhost:8080/api/v1/profile/updateByProfile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5MDk1MjcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5OTU5MjcsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.NajD-X4FaRzEwPEs00Y9MZ_HkMC6gkfy4YZkJ2Hw_3SEZn0R4OVFD6QKcYpbi9P4pBal1zxC8bDIemjEdFzMSg
Content-Type:  application/json

{
  "id": 2,
  "name": "Toshmat",
  "surname": "Toshmatov",
  "email": "toshmat@mail.ru",
  "phone": "121345",
  "password": "1",
  "role": "PUBLISHER",
  "status": "ACTIVE",
  "visible": "true"
}

### Update profle
PUT localhost:8080/api/v1/profile/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIyNDI5MjIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIzMjkzMjIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1hcud2opIwScYKp1s8B7N5XIv_oAkIul_ElmT2IS_7bWZv2U50DBMmDdR7tKGh3ogfVuMr_JAVNJ8up16dHvtA
Content-Type:  application/json

{
  "id": 1,
  "name": "Admin",
  "surname": "Adminov",
  "email": "admin@mail.ru",
  "phone": "1",
  "password": "1",
  "role": "ADMIN",
  "status": "ACTIVE",
  "visible": true
}

### profile List
GET http://localhost:8080/api/v1/profile/getProfileList

### List profle
PUT localhost:8080/api/v1/profile/paging
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5MDk1MjcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5OTU5MjcsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.NajD-X4FaRzEwPEs00Y9MZ_HkMC6gkfy4YZkJ2Hw_3SEZn0R4OVFD6QKcYpbi9P4pBal1zxC8bDIemjEdFzMSg
Content-Type:  application/json

### List profle
PUT localhost:8080/api/v1/profile/delete/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5MDk1MjcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5OTU5MjcsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.NajD-X4FaRzEwPEs00Y9MZ_HkMC6gkfy4YZkJ2Hw_3SEZn0R4OVFD6QKcYpbi9P4pBal1zxC8bDIemjEdFzMSg
Content-Type:  application/json

### Course filter
POST localhost:8080//api/v1/profile/filter
Content-Type: application/json

{
  "name": "Ali"
}

