### Create profle
POST localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI2OTU2MDIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI3ODIwMDMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.yvTLeG6ANXkTJi1UdipJr_Sc9amSNouWglmZqoZJMOlNJkMdv4qDya98znc9zzKtlEFO-RQx4d31CrCnFV2IpA
Content-Type:  application/json

//{
//  "name": "Ali",
//  "surname": "Aliyev",
//  "email": "ali@mail.ru",
//  "phone": "2",
//  "password": "2",
//  "role": "MODERATOR"
//}
{
  "name": "Toshmat",
  "surname": "Toshmatov",
  "email": "toshmat@mail.ru",
  "phone": "4",
  "password": "4",
  "role": "PUBLISHER"
}

### Update profle
PUT localhost:8080/api/v1/profile/updateByProfile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI2OTY5MDEsImlkIjo1LCJyb2xlIjoiUFVCTElTSEVSIiwiZXhwIjoxNjgyNzgzMzAxLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.ojPYZlcoQstyL2J3QGlVjUhXh8suJKzFozbqIXylEKRC1fRaTqnUVTvxPawebaXQUqJj__4AT72wfJTu01FOiQ
Content-Type:  application/json

{
  "name": "Mamat",
  "surname": "Mamatov",
  "email": "mamat@mail.ru",
  "phone": "5",
  "password": "5",
  "role": "ADMIN",
  "status": "ACTIVE",
  "visible": "true"
}

### Update profle
PUT localhost:8080/api/v1/profile/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI2OTU2MDIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI3ODIwMDMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.yvTLeG6ANXkTJi1UdipJr_Sc9amSNouWglmZqoZJMOlNJkMdv4qDya98znc9zzKtlEFO-RQx4d31CrCnFV2IpA
Content-Type:  application/json

{
  "id": 1,
  "name": "Admin",
  "surname": "Adminov",
  "email": "admin@mail.ru",
  "phone": "1",
  "password": "1",
  "role": "ADMIN",
  "status": "ACTIVE",
  "visible": true
}

### profile List
GET http://localhost:8080/api/v1/profile/getProfileList

### List profle
PUT localhost:8080/api/v1/profile/paging
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI2OTU2MDIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI3ODIwMDMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.yvTLeG6ANXkTJi1UdipJr_Sc9amSNouWglmZqoZJMOlNJkMdv4qDya98znc9zzKtlEFO-RQx4d31CrCnFV2IpA
Content-Type:  application/json

### List profle
PUT localhost:8080/api/v1/profile/delete/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI2OTU2MDIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI3ODIwMDMsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.yvTLeG6ANXkTJi1UdipJr_Sc9amSNouWglmZqoZJMOlNJkMdv4qDya98znc9zzKtlEFO-RQx4d31CrCnFV2IpA
Content-Type:  application/json

### Course filter
POST localhost:8080//api/v1/profile/filter
Content-Type: application/json

{
  "name": "Ali"
}

### Update Photoprofle
PUT localhost:8080/api/v1/profile/updatePhoto/7f0dcb2e-d5f2-4c17-8d61-9f381c48078e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI2MDI1OTAsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgyNjg4OTkxLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.TzLaejKAA7es3kvaQXuh2sQiJUtoSXP8TQ8cie4Gu45dLPNnpBmV2w1bly3vkl1CH97B-7FLgOoJbXJsyCUEZg
Content-Type:  application/json


