### Create Region
POST localhost:8080/api/v1/region
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

//{
//  "nameUz": "Toshkent",
//  "nameRu": "Ташкент",
//  "nameEng": "Tashkent",
//  "visible": true
//}
//{
//  "nameUz": "Navoiy",
//  "nameRu": "Наваи",
//  "nameEng": "Navai",
//  "visible": true
//}
//{
//  "nameUz": "Buxoro",
//  "nameRu": "Бухара",
//  "nameEng": "Bukhara",
//  "visible": true
//}
{
  "nameUz": "Xorazm",
  "nameRu": "Харезм",
  "nameEng": "Xarezm",
  "visible": true
}
### Update Region
PUT localhost:8080/api/v1/region/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

{
  "id" : 4,
  "nameUz": "Andijon",
  "nameRu": "Андижан",
  "nameEng": "Andijhan",
  "visible": true
}

### List Region
PUT localhost:8080/api/v1/region/delete/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

### Paging Region
PUT localhost:8080/api/v1/region/paging
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json

### GetByLang Region
PUT localhost:8080/api/v1/region/getByLang/Eng
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDk3MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4MzYxMjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Lf0IGwyvBxSXEoXhteUrYjziUH2jYiYoX0lw5y--rpQqrHVwWBDTNxu_wS-h2QmeiFORyUhgkEQWyLmpD6cEZA
Content-Type:  application/json